[package]
authors = ["Adeoye Adefemi <adefemiadeoye@yahoo.com>"]
description = "An Authentication, Authorization and Identity Management system for microservices  https://github.com/opeolluwa/racoon"
edition = "2021"
name = "racoon"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-graphql = {version = "3.0.12"}
async-session = "3.0.0"
async-trait = "0.1.57"
axum = {version = "0.5.16", features = ["headers", "json", "ws"]}
bcrypt = "0.13.0"
chrono = {version = "0.4.22", features = ["serde"]}
console = "0.15.2"
dotenv = "0.15.0"
futures = "0.3.23"
headers = "0.3.8"
http-body = "0.4.5"
jsonwebtoken = "8.1.1"
lettre = "0.10.1"
once_cell = "1.15.0"
ormlite = {version = "0.9", features = ["postgres", "runtime-tokio-rustls"]}
otp-rs = "0.1.1"
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"
sqlx = {version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "any", "uuid", "migrate", "chrono", "time"]}
thiserror = "1.0.29"
tokio = {version = "1.20.1", features = ["full"]}
tower-http = {version = "0.3.4", features = ["cors", "fs", "trace"]}
tracing = "0.1.36"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
uuid = {version = "1.1.2", features = ["serde", "v4"]}
validator = {version = "0.16.0", features = ["derive"]}


